version: "3.9"
services: 
  mysql:
    build: ./mysql/
    ports: 
      - "3306:3306"
    restart: always
    container_name: mysql
    volumes: 
      - "/home/ubuntu/nuskusa-infra/mysql/volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080

  express: 
    build: ./express/
    container_name: express
    ports: 
      - "3000:3000"
    depends_on:
      - mysql
    restart: always
    environment:
      - PKR_VAR_MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PKR_VAR_MYSQL_USER=$MYSQL_USER
      - PKR_VAR_MYSQL_PASSWORD=$MYSQL_PASSWORD
      - PKR_VAR_MYSQL_DATABASE=$MYSQL_DATABASE

  nginx:
    build: ./nginx/
    stdin_open: true # docker run -i
    container_name: nginx
    depends_on: 
      - express
    ports: 
      - "80:80"
      - "443:443"
    restart: always
