version: "3.9"
services:
  jenkins:
    build: .
    container_name: jenkins
    volumes:
      - "/jenkins:/var/lib/jenkins"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8000:8080"
    tty: true
    user: root
    stdin_open: true
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
