pipeline {
    agent any
    
    environment {
        BackendGitUrl = "https://github.com/NUS-Korea-Society/nuskusa-backend"
        InfraGitUrl = "https://github.com/NUS-Korea-Society/nuskusa-infra-single.git"
    }
    
    stages {
        stage("Remove previous versions") {
            steps {
                sh 'rm -rf nuskusa-*'
            }
        }
        
        stage("Pull") {
            steps {
                dir("nuskusa-infra-single") {
                    git url: "${InfraGitUrl}", branch: "main", poll: true, changelog: true
                }
            }
        }
        
        stage("Deploy") {
            steps {
                dir("nuskusa-infra-single") {
                    sh 'sudo -E docker compose down'
                    sh 'sudo -E docker compose up -d --build'
                }
            }
        }

        stage("Finish") {
            steps {
                sh 'docker images -qf dangling=true | xargs -I{} docker rmi {}'
            }
        }
    }
}
