name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: trigger jenkins nuskusa job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://nuskoreasociety.org:8000"
        user: "nuskusa-admin"
        token: "${{ secrets.JENKINS_TOKEN }}"
        job: "nuskusa-infra-single"
